### ISSUE TITLE
Spec out Helium API expected behavior

### ISSUE THREAD

**Issue by aflinchb** [retaildevcrews/helium#243]
# Design Review

## Introduction
- [x]  Spec out expected behavior of each Helium API call (including edge/failing cases)
- [x]  Have meeting to review with team and agree on spec
- [x] Create tasks as needed to update the 3 versions
- [x] Add link to design documentation

### Design Review Checklist

- [x] Design Review Meeting Scheduled
- [x] Design Review approved by team consensus
- [x] Initial tasks created as issues in main project and assigned to the project backlog with proper priority
- [x] Test plan complete (unit, validation, smoke)
- [x] References *insert all references to tasks here*

References #
retaildevcrews/webvalidate#24
retaildevcrews/helium-typescript#69
retaildevcrews/helium-typescript#70
retaildevcrews/helium-csharp#55
retaildevcrews/helium-csharp#54

**Comment by jyotsnaravikumar** [comment]
Next steps : 5 new tasks created to add the expected behavior to C#, type script APIs, webV tests.

References #
https://github.com/retaildevcrews/webvalidate/issues/24
https://github.com/retaildevcrews/helium-typescript/issues/69
https://github.com/retaildevcrews/helium-typescript/issues/70
https://github.com/retaildevcrews/helium-csharp/issues/55
https://github.com/retaildevcrews/helium-csharp/issues/54
