### ISSUE TITLE
smoker ACI instances do not restart upon an 0 exit code

### ISSUE THREAD

**Issue by evillgenius75** [retaildevcrews/helium#273]
## Description
- The current policy for restart of the smoker instances is `OnFailure` which will only restart the container if the process exited with anything other than a 0 code. This could leave an instance of smoker to be turned off and never restarted.

## Expected Behavior
- ACI will restart the container instance no matter what happens

## Additional Context 
- Fix is to recreate instances with new policy of `Always`

**Comment by evillgenius75** [comment]
@retaildevcrews/helium I will need to take down the webv for each instance to clear this bug. There will be a gap in reporting for all instances for roughly 5-10 minutes today.

**Comment by bartr** [comment]
We should figure out why WebV exited with a 0. It should exit with a -1 on any type of failure. That is relatively new code, so could already be fixed. Do you have the logs of what happened in webv to cause it to exit?

I think I would leave it as-is for now so that we can make sure webv is exiting correctly.

**Comment by evillgenius75** [comment]
latest version of webv has been running for 48hours with new version and the containers have not restarted. Seems bug was related to specificlaly gelato and the error logging threshold
