### ISSUE TITLE
Drain all connections before app shutdown

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/helium#383]
#Description
drain all connections before app shutdown

Languages
- [x] csharp
- [x] typescript
- [x] java

**Comment by sivamu** [comment]
For java, using the inbuilt [spring app property](https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/html/spring-boot-features.html#boot-features-graceful-shutdown) to enable graceful shutdown.

**Comment by sivamu** [comment]
For node, `server.close` only completes when existing requests are processed. Adding some timeout behavior on top of that to complete the graceful shutdown impl.

**Comment by sivamu** [comment]
### C#
Didn't remove the ctrl-c handler since it's being used for `RunKeyRotationCheck` and the server `Stop()` method. Since `IWebHost` is defined on `IHostedService` interface, I was able to take advantage of the native `StopAsync()` method to manually trigger a [graceful shutdown](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-3.1&tabs=visual-studio#ihostedservice-interface).
