### ISSUE TITLE
Update 'Direct Reads' to return same response as 'Searches' (empty array vs. 404)

### ISSUE THREAD

**Issue by jasonshave** [retaildevcrews/helium#562]
Currently a valid query parameter search of `Actors` or `Movies` returns an empty array with an `HTTP/200` and content-type of `application/json`.

A valid query to the 'direct read' (route path) for `Actors` or `Movies` returns an `HTTP/404` and content-type of `application/json`.

Objectives:

- Create a consistent return of an `HTTP/200` empty array, similar to how the searching API behaves.
- Update validation documentation.
- Update web validate tests

Tasks:

- [ ] Gather feedback from team
- [ ] Update C# code
- [ ] Update Java code
- [ ] Update TypeScript code
- [ ] Update bad.json for web validate tests
- [ ] Update [ParamterValidation](https://github.com/retaildevcrews/helium/blob/main/docs/ParameterValidation.md) documentation

**Comment by bartr** [comment]
We researched and discussed this during the initial design and 404 is the correct response because it's a URI.

/foo will return a 404
/api/actors/foo should return 400 if foo is invalid and 404 if foo doesn't exist.

Returning [] would not be correct also because the URL is for a single actor document, not an array of documents.

Here's an example:  curl -I https://api.github.com/orgs/foo
